
package org.nasa.ws.proxy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "SSCResourceLimitExceededException", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/")
public class SSCResourceLimitExceededException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SSCResourceLimitExceededException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SSCResourceLimitExceededException_Exception(String message, SSCResourceLimitExceededException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SSCResourceLimitExceededException_Exception(String message, SSCResourceLimitExceededException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.nasa.ws.proxy.SSCResourceLimitExceededException
     */
    public SSCResourceLimitExceededException getFaultInfo() {
        return faultInfo;
    }

}
