
package org.nasa.ws.proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SatelliteSituationCenterInterface", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/")
public interface SatelliteSituationCenterInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.nasa.ws.proxy.DataResult
     * @throws SSCResourceLimitExceededException_Exception
     * @throws SSCExternalException_Exception
     * @throws SSCDatabaseLockedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getData", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetDataResponse")
    public DataResult getData(
        @WebParam(name = "arg0", targetNamespace = "")
        DataRequest arg0)
        throws SSCDatabaseLockedException_Exception, SSCExternalException_Exception, SSCResourceLimitExceededException_Exception
    ;

    /**
     * 
     * @return
     *     returns org.nasa.ws.proxy.FileResult
     * @throws SSCExternalException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrivacyAndImportantNotices", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetPrivacyAndImportantNotices")
    @ResponseWrapper(localName = "getPrivacyAndImportantNoticesResponse", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetPrivacyAndImportantNoticesResponse")
    public FileResult getPrivacyAndImportantNotices()
        throws SSCExternalException_Exception
    ;

    /**
     * 
     * @return
     *     returns org.nasa.ws.proxy.FileResult
     * @throws SSCExternalException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAcknowledgements", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetAcknowledgements")
    @ResponseWrapper(localName = "getAcknowledgementsResponse", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetAcknowledgementsResponse")
    public FileResult getAcknowledgements()
        throws SSCExternalException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<org.nasa.ws.proxy.SpaseObservatoryDescription>
     * @throws SSCExternalException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSpaseObservatories", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetAllSpaseObservatories")
    @ResponseWrapper(localName = "getAllSpaseObservatoriesResponse", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetAllSpaseObservatoriesResponse")
    public List<SpaseObservatoryDescription> getAllSpaseObservatories()
        throws SSCExternalException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<org.nasa.ws.proxy.GroundStationDescription>
     * @throws SSCExternalException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllGroundStations", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetAllGroundStations")
    @ResponseWrapper(localName = "getAllGroundStationsResponse", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetAllGroundStationsResponse")
    public List<GroundStationDescription> getAllGroundStations()
        throws SSCExternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.nasa.ws.proxy.FileResult
     * @throws SSCResourceLimitExceededException_Exception
     * @throws SSCExternalException_Exception
     * @throws SSCDatabaseLockedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGraphs", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetGraphs")
    @ResponseWrapper(localName = "getGraphsResponse", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetGraphsResponse")
    public FileResult getGraphs(
        @WebParam(name = "arg0", targetNamespace = "")
        GraphRequest arg0)
        throws SSCDatabaseLockedException_Exception, SSCExternalException_Exception, SSCResourceLimitExceededException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.nasa.ws.proxy.FileResult
     * @throws SSCExternalException_Exception
     * @throws SSCResourceLimitExceededException_Exception
     * @throws SSCDatabaseLockedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDataFiles", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetDataFiles")
    @ResponseWrapper(localName = "getDataFilesResponse", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetDataFilesResponse")
    public FileResult getDataFiles(
        @WebParam(name = "arg0", targetNamespace = "")
        DataFileRequest arg0)
        throws SSCDatabaseLockedException_Exception, SSCExternalException_Exception, SSCResourceLimitExceededException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<org.nasa.ws.proxy.SatelliteDescription>
     * @throws SSCExternalException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSatellites", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetAllSatellites")
    @ResponseWrapper(localName = "getAllSatellitesResponse", targetNamespace = "http://ssc.spdf.gsfc.nasa.gov/", className = "org.nasa.ws.proxy.GetAllSatellitesResponse")
    public List<SatelliteDescription> getAllSatellites()
        throws SSCExternalException_Exception
    ;

}
